# set up common packages
---

- name: Install ru_RU.UTF-8 locale
  locale_gen: name=ru_RU.UTF-8 state=present

- name: Install en_US.UTF-8 locale
  locale_gen: name=en_US.UTF-8 state=present

- name: Install common staff
  apt:
    name: "{{ item }}"
    state: 'present'
    update_cache: True
  with_items:
    - software-properties-common
    - python-apt
    - htop
    - mc
    - rsync
    - sudo
    - git-core
    - zip
    - unzip
    - ca-certificates
    - screen
    - curl
    - vim
    - chrony
    - speedtest-cli

- name: Removing ntpd
  apt:
    name: ntpd
    state: absent

- name: Running chrony
  service:
    name: chrony
    state: restarted
    enabled: yes
 
